//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMSApi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ffrDevEntities : DbContext
    {
        public ffrDevEntities()
            : base("name=ffrDevEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CodeFrdUnit> CodeFrdUnits { get; set; }
        public virtual DbSet<CodeVFrdWorkGroupWBattalion> CodeVFrdWorkGroupWBattalions { get; set; }
        public virtual DbSet<EMSCategory> EMSCategories { get; set; }
        public virtual DbSet<EMSComplaint> EMSComplaints { get; set; }
        public virtual DbSet<EMSVCategory> EMSVCategories { get; set; }
        public virtual DbSet<EMSVComplaint> EMSVComplaints { get; set; }
        public virtual DbSet<EMSSupplementalDOC> EMSSupplementalDOCs { get; set; }
        public virtual DbSet<EMSNote> EMSNotes { get; set; }
    }
}
