//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMSApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMSSupplementalDOC
    {
        public int DocId { get; set; }
        public Nullable<int> ComplaintId { get; set; }
        public string DocType { get; set; }
        public string DocName { get; set; }
        public string DocDesc { get; set; }
        public string DocDescOther { get; set; }
        public string DocExt { get; set; }
        public byte[] Doc { get; set; }
        public byte[] ImageDoc { get; set; }
        public string DocLocation { get; set; }
        public string Comments { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
    }
}
