//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMSApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CodeFrdUnit
    {
        public int Id { get; set; }
        public string Unit { get; set; }
        public Nullable<int> WorkGroupId { get; set; }
        public string WorkGroupAbbrv { get; set; }
    }
}
