//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMSApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CodeVFrdWorkGroupWBattalion
    {
        public int Id { get; set; }
        public string WorkGroupAbbrv { get; set; }
        public string WorkGroupName { get; set; }
        public string WorkGroupDesc { get; set; }
        public string PSMACode { get; set; }
        public string LocationCode { get; set; }
        public string IndexCode { get; set; }
        public string EMSIndexCode { get; set; }
        public string CodeAssociation { get; set; }
        public string PhoneNo { get; set; }
        public string Fax { get; set; }
        public string Pager { get; set; }
        public string CellPhone { get; set; }
        public Nullable<bool> IsStation { get; set; }
        public Nullable<bool> IsVolStation { get; set; }
        public string Building { get; set; }
        public string StreetNum { get; set; }
        public string StreetName { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ZipCode { get; set; }
        public Nullable<bool> IsHistory { get; set; }
        public string Comments { get; set; }
        public string FOCUSWorkLocationCode { get; set; }
        public Nullable<int> ParentId { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string battalion { get; set; }
    }
}
